language: groovy
jdk:
- oraclejdk8
install: true
before_script:
- chmod 755 grailsw
- chmod 755 gradlew
script:
- "./grailsw clean"
- "./grailsw test-app"
- "./grailsw package"
- "mv build/libs/CS481-Project-0.1.war CS481-Project-0.1.war"
- "./gradlew deployBeta"
